<?php
namespace Arura;
use Arura\Exceptions\Error;
use Mpdf\Mpdf;

class PDF extends Mpdf {

    protected $template;
    protected $oSmarty;

    public function __construct(array $config = [])
    {
        parent::__construct($config);
        $this->oSmarty = new \Smarty();
    }

    public function setTemplate($sFile){
        if (is_file($sFile)){
            $this->WriteHTML($this->oSmarty->fetch($sFile));
        } else {
            throw new Error("Template file not valid");
        }
    }

    public function assign($sName, $sValue){
        $this->oSmarty->assign($sName,$sValue);
    }

    public function SetHTMLHeader($header = '', $OE = '', $write = false)
    {
        return parent::SetHTMLHeader($this->oSmarty->fetch($header), $OE, $write); // TODO: Change the autogenerated stub
    }

    public function SetHTMLFooter($footer = '', $OE = '')
    {
        return parent::SetHTMLFooter($this->oSmarty->fetch($footer), $OE); // TODO: Change the autogenerated stub
    }

    public function Output($name = '', $dest = '')
    {
        return parent::Output($name, $dest);
    }
}